development:
  store:
    type: mongodb
    uri: mongodb://localhost:27017
    database: devdb

production:
  store:
    type: postgres
    uri: postgres://user:pass@host:5432/proddb
    database: proddb 