name: CI/CD Pipeline

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build and Test
      env:
        GITHUB_TOKEN: ${{ github.token }}  # Using default GitHub token
      run: |
        go build ./...
        go test ./... 