name: Security Secrets Scan

## Add permissions block to fix the "Resource not accessible" error
permissions:
  contents: read
  issues: write    ## Needed for creating issues
  security-events: write  ## Needed for security scanning

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:
    inputs:
      scan-depth:
        description: 'Scanning depth (quick/full)'
        required: true
        default: 'quick'

jobs:
  security-check:
    name: Security Secrets Scanner
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Run GoSec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...

    - name: Build and Test
      run: |
        go build ./...
        go test ./...
        
    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Security Scan Failed',
            body: 'The security scan workflow failed. Please check the Actions tab for details.'
          })